### ISSUE TITLE
Не копирует дириктории начинающиеся с точки

### ISSUE THREAD

**Issue by omqmo** [MrMeison/yc-object-storage-action#118]
В проекте существует директория название которой начинается с точки и данный экшен её не копирует...
и стоит упомянуть, что в этой директории находится файл без расширения. И это не изменяемо, так как подобное требует яндекс при добавлении генерируемого сертификата от LETS_ENCRYPT (возможно и от других, например cname тоже не имеет расширения).

**Comment by MrMeison** [comment]
Добавлено в релизе 1.1.0
